### ISSUE TITLE
docker-compose 추가에 대한 의견

### ISSUE THREAD

**Issue by wooogieee** [Q00/api_server_boilerplate#18]
docker-compose를 작성하여 조금 더 간결화 시키는건 어떨까요?

**Comment by Q00** [comment]
의견 감사합니다!
이슈 템플릿 만들어서 올릴 예정이었는데 이슈 달아주셨네요! 
docker-compose 작성해서 간결화 하도록 하겠습니다 :)
혹시나 의견 있으시면 pr 날려주셔도 됩니다 !

**Comment by Q00** [comment]
추가했습니다 :)
